<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minion">
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="green">
    <color rgba="0 0.8 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Constants-->
  <xacro:property name="namespace"       value="$(arg namespace)" />
  <xacro:property name="chassis_mass"    value="2.5" />
  <xacro:property name="chassis_length"  value="0.3" />
  <xacro:property name="chassis_width"   value="0.25" />
  <xacro:property name="chassis_height"  value="0.06" />
  <xacro:property name="battery_mass"    value="0.05" />
  <xacro:property name="battery_length"  value="0.07" />
  <xacro:property name="battery_width"   value="0.05" />
  <xacro:property name="battery_height"  value="0.05" />
  <xacro:property name="wheel_thickness" value="0.02" />
  <xacro:property name="wheel_mass"      value="0.5" />

  <xacro:property name="piston_moving_r"      value="0.02" />
  <xacro:property name="piston_moving_h"      value="0.30" />
  <xacro:property name="piston_moving_m"      value="0.35" />


  <!-- More Constants -->
  <xacro:property name="lwid" value="left_wheel"/>
  <xacro:property name="rwid" value="right_wheel"/>
  <xacro:property name="ID" value="0"/>
  <xacro:property name="wheel_radius" value="0.06"/>
  <xacro:property name="joint_height" value="0.025"/>

  <xacro:macro name="wheel_inertia" params="mass">
      <inertial>
          <mass value="${mass}" />
          <inertia ixx="${mass*(3*wheel_radius*wheel_radius+wheel_thickness*wheel_thickness)/12}" ixy="0.0" ixz="0.0" iyy="${mass*(3*wheel_radius*wheel_radius+wheel_thickness*wheel_thickness)/12}" iyz="0.0" izz="${mass*wheel_radius*wheel_radius/2}"/>
      </inertial>
  </xacro:macro>

  <xacro:macro name="wheel_link" params="id radius thickness color mass">
    <link name="${namespace}/${id}">
      <inertial>
          <mass value="${wheel_mass}"/>
          <inertia ixx="${wheel_mass*(3*radius*radius + thickness*thickness)/12}"  ixy="0"  ixz="0" iyy="${wheel_mass*(3*radius*radius + thickness*thickness)/12}" iyz="0" izz="${wheel_mass*(radius*radius)/2}" /> 
      </inertial>

      <visual>
        <geometry>
          <cylinder length="${thickness}" radius="${radius}"/>
        </geometry>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      </visual>

      <material name="${color}"/>

      <collision>
        <geometry>
          <cylinder length="${thickness}" radius="${radius}"/>
        </geometry>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      </collision>

      <xacro:wheel_inertia mass="${wheel_mass}"/>
    </link>

    <gazebo reference="${namespace}/${id}">
      <mu value="200"/>
      <mu2 value="200"/>
      <kp value="4000.0" />
      <kd value="100.0" />
      <material>Gazebo/White</material>
    </gazebo>
  </xacro:macro>


  <xacro:macro name="wheel_joint" params="id child x y z">
   <joint name="${id}" type="continuous">
     <parent link="${namespace}/base_link"/>
     <child link="${namespace}/${child}"/>
     <origin xyz="${x} ${y} ${z}"/>
     <axis xyz="0 1 0"/>
     <!--limit effort="0.13" velocity="621"/-->
     <!--safety_controller k_velocity="0.0002"/-->
   </joint>
  </xacro:macro>


  <transmission name="pt">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="ptptpt">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="base_piston_moving">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> 
<!--       <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
 -->    </joint>
  </transmission>

 <xacro:macro name="wheel_joint_transmission" params="id">
  <transmission name="${id}_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="${id}_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="${id}">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>
  </xacro:macro>

  <link name="${namespace}/base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 ${joint_height}"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${joint_height}"/>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <inertia ixx="${chassis_mass*chassis_width*chassis_width/12+chassis_mass*chassis_height*chassis_height/12}" ixy="0.0" ixz="0.0"
        iyy="${chassis_mass*chassis_length*chassis_length/12+chassis_mass*chassis_height*chassis_height/12}" iyz="0.0"
        izz="${chassis_mass*chassis_length*chassis_length/12+chassis_mass*chassis_width*chassis_width/12}"/>
    </inertial>
  </link>
  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/Orange</material>
  </gazebo>





  <link name="${namespace}/piston_fixed">
      <inertial>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
          <mass value="0.4"/> 
      </inertial>
      <collision name="collision">
          <geometry>
            <cylinder length="0.3" radius="0.03"/>
          </geometry>
      </collision>
      <visual name="visual">
          <geometry>
            <cylinder length="0.3" radius="0.03"/>
          </geometry>
          <material name="blue"/>
<!--             <color rgba="0 1.0 1.0 1.0"/>
          </material> -->
      </visual>
  </link>

  <gazebo reference="${namespace}/piston_fixed">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="${namespace}/base_piston_fixed" type="fixed">
     <parent link="${namespace}/base_link"/>
     <child link="${namespace}/piston_fixed"/>
     <origin xyz="${0} 0 ${chassis_height + 0.13}"/>
  </joint>  

  <link name="${namespace}/piston_moving">
      <inertial>
          <inertia ixx="${piston_moving_m*((3*piston_moving_r*piston_moving_r) + (piston_moving_h*piston_moving_h))/12}" ixy="0" ixz="0" iyy="${piston_moving_m*((3*piston_moving_r*piston_moving_r) + (piston_moving_h*piston_moving_h))/12}" iyz="0" izz="${0.5*piston_moving_m*piston_moving_r*piston_moving_r}"/>
          <mass value="${piston_moving_m}"/> 
      </inertial>
      <collision name="collision">
          <geometry>
            <cylinder length="${piston_moving_h}" radius="${piston_moving_r}"/>
          </geometry>
      </collision>
      <visual name="visual">
          <geometry>
            <cylinder length="${piston_moving_h}" radius="${piston_moving_r}"/>
          </geometry>
      </visual>
  </link>

  <gazebo reference="${namespace}/piston_moving">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="base_piston_moving" type="prismatic">
     <parent link="${namespace}/piston_fixed"/>
     <child link="${namespace}/piston_moving"/>
     <provide_feedback>true</provide_feedback>
     <limit effort="1000" lower="0" upper="10" velocity="0.03"/>
     <origin xyz="0 0 ${chassis_height}"/>
     <origin xyz="0 0 ${chassis_height + 0}"/>
     <axis xyz="0 0 1"/>
  </joint> 

  <link name="${namespace}/piston_plate">
      <inertial>
          <mass value="0.2"/>
          <inertia ixx="${0.2*(.3*.3 + 0.01*0.01)/12}"  ixy="0"  ixz="0" iyy="${0.2*(.3*.3 + 0.01*0.01)/12}" iyz="0" izz="${0.2*(.3*.3 + .3*.3)/12}" /> 
      </inertial>

      <collision name="collision">
          <geometry>
            <box size="0.3 0.3 0.025"/>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu1>1000000</mu1>
                <mu2>1000000</mu2>
                <kp value="1000" />
                <kd value="1000" />
              </ode>
            </friction>
          </surface>
      </collision>

      <visual name="visual">
          <geometry>
            <box size="0.3 0.3 0.01"/>
          </geometry>
          <material name="Red"/>
      </visual>

  </link>

  <gazebo reference="${namespace}/piston_plate">
    <material>Gazebo/Black</material>
    <mu1>1000</mu1>
    <mu2>1000</mu2>
    <kp value="1000" />
    <kd value="1000" />
 </gazebo>

<!-- original  -->
<!--   <joint name="${namespace}/base_piston_plate" type="fixed">
     <parent link="${namespace}/piston_moving"/>
     <child link="baseplate"/> 
     <origin xyz="0 0 ${chassis_height + 0.04}"/>
  </joint>  
 -->
<!-- original end -->

<!-- https://answers.ros.org/question/258420/ball-joint-in-urdf/ -->

<!-- type 1 start -->
  <joint name="${namespace}/base_piston_plate" type="revolute">
    <parent link="${namespace}/piston_moving"/>
    <child link="${namespace}/junta1"/>
    <axis xyz="0 1 0" />
    <dynamics damping="0.05" friction="0.015"/>
    <limit effort="500" velocity="1.0" lower="-0.2" upper="0.2" />
<!--     <origin xyz="0 0 ${chassis_height + 0.055}"/>
 -->    <origin xyz="0 0 ${chassis_height + 0.11}"/>
  </joint>

  <link name="${namespace}/junta1">
    <inertial>
      <mass value="0.02" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>
  </link>

  <joint name="${namespace}_joint2" type="revolute">
    <parent link="${namespace}/junta1"/>
    <child link="${namespace}/junta2"/>
    <axis xyz="0 0 1" />
    <dynamics damping="0.05" friction="0.015"/>
    <limit effort="500" velocity="1.0" lower="-0.2" upper="0.2" />
  </joint>

  <link name="${namespace}/junta2">
    <inertial>
      <mass value="0.02" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>  
  </link>

  <joint name="${namespace}_joint3" type="revolute">
    <parent link="${namespace}/junta2"/>
    <child link="${namespace}/junta3"/>
    <axis xyz="1 0 0" />
    <dynamics damping="0.05" friction="0.015"/>
    <limit effort="500" velocity="1.0" lower="-0.2" upper="0.2" />
  </joint>

  <link name="${namespace}/junta3">
    <inertial>
      <mass value="0.02" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>  
  </link>

<joint name="${namespace}_jointfixed" type="fixed"> 
    <parent link="${namespace}/junta3"/>
    <child link="${namespace}/piston_plate"/>
 -->  </joint>
<!-- type 1 end -->



<!-- type 2 start -->

<!--   <joint name="${namespace}/base_piston_plate" type="fixed">
     <parent link="${namespace}/piston_moving"/>
     <child link="baseplate"/>
     <limit effort="100" lower="0" upper="10" velocity="0.01"/> 
     <origin xyz="0 0 ${chassis_height + 0.04}"/>
  </joint>  

  <link name="baseplate">
    <inertial>
      <mass value="0.025" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>  
  </link>

  <joint name="PistonPsi" type="continuous" >
      <parent link="baseplate" />
      <child link="Piston_psi_link" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.005" />
  </joint>

  <link name="Piston_psi_link">
    <inertial>
      <mass value="0.025" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>  
  </link>

  <joint name="PistonTheta" type="continuous" >
      <parent link="Piston_psi_link"/>
      <child link="Piston_theta_link"/>
      <axis xyz="0 1 0" />
      <dynamics damping="0.005" />
  </joint>

  <link name="Piston_theta_link">
    <inertial>
      <mass value="0.025" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>  
  </link>

  <joint name="PistonPhi" type="continuous" >
      <parent link="Piston_theta_link"/>
      <child link="${namespace}/piston_plate"/>
      <axis xyz="1 0 0" />
      <dynamics damping="0.005" />
    </joint>
 -->
<!-- type 2 end -->


<!-- 
   <link name="${namespace}/castor">
    <inertial>
      <mass value="0.025" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial> 
    
    <visual>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="${namespace}/castor">
    <slip1 value="1"/>
    <slip2 value="1"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="${namespace}/base_castor" type="fixed">
     <parent link="${namespace}/base_link"/>
     <child link="${namespace}/castor"/>
     <origin xyz="${chassis_length/2-wheel_radius} 0 ${joint_height}"/>
  </joint> -->

  <!--Left Side-->
  <xacro:wheel_link id="${lwid}_${ID+1}" radius="${wheel_radius}" thickness="${wheel_thickness}" color="orange" mass="${wheel_mass}"/>
  <xacro:wheel_joint id="blw_${ID+1}" child="${lwid}_${ID+1}" x="${-chassis_length/2+0.03}" y="${chassis_width/2+0.02}" z="${joint_height}"/>
  <xacro:wheel_joint_transmission id="blw_${ID+1}"/>

  <xacro:wheel_link id="${lwid}_${ID+0}" radius="${wheel_radius}" thickness="${wheel_thickness}" color="orange" mass="${wheel_mass}"/>
  <xacro:wheel_joint id="blw_${ID+0}" child="${lwid}_${ID+0}" x="${chassis_length/2-0.03}" y="${chassis_width/2+0.02}" z="${joint_height}"/>
  <!-- <xacro:wheel_joint_transmission id="blw_${ID+0}"/> -->




  <!--Right Side-->
  <xacro:wheel_link id="${rwid}_${ID+1}" radius="${wheel_radius}" thickness="${wheel_thickness}" color="orange" mass="${wheel_mass}"/>
  <xacro:wheel_joint id="brw_${ID+1}" child="${rwid}_${ID+1}" x="${-chassis_length/2+0.03}" y="${-chassis_width/2-0.02}" z="${joint_height}"/>
  <xacro:wheel_joint_transmission id="brw_${ID+1}"/>


  <xacro:wheel_link id="${rwid}_${ID+0}" radius="${wheel_radius}" thickness="${wheel_thickness}" color="orange" mass="${wheel_mass}"/>
  <xacro:wheel_joint id="brw_${ID+0}" child="${rwid}_${ID+0}" x="${+chassis_length/2-0.03}" y="${-chassis_width/2-0.02}" z="${joint_height}"/>
  <!-- <xacro:wheel_joint_transmission id="brw_${ID+0}"/> -->




  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    </plugin>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>${namespace}/base_link</bodyName>
      <topicName>imu</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>20.0</updateRate>
    </plugin>

    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>50.0</updateRate>
      <bodyName>${namespace}/base_link</bodyName>
      <topicName>ground_truth_pose</topicName>
      <gaussianNoise>0.01</gaussianNoise>
      <frameName>world</frameName>
      <xyzOffsets>0 0 0</xyzOffsets>
      <rpyOffsets>0 0 0</rpyOffsets>
    </plugin>

  </gazebo>

</robot>